import 'experience_card_model.dart';

final List<ExperienceCardModel> mockCards = [
  const ExperienceCardModel(
    id: '1',
    title: 'Blue Bottle Coffee',
    imageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=600&q=80&fit=crop',
    rating: 4.5,
    category: ExperienceCategory.cafe,
    comment: 'Great atmosphere, perfect for a short break.',
    authorName: 'Alex',
    authorAvatarUrl: 'https://i.pravatar.cc/150?u=alex',
    duration: '1h',
    priceRange: '\$\$',
    tags: ['Relaxing', 'Good Coffee'],
  ),
  const ExperienceCardModel(
    id: '2',
    title: 'Kyoto Imperial Palace',
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80&fit=crop',
    rating: 4.8,
    category: ExperienceCategory.sightseeing,
    comment: 'Beautiful gardens and historic buildings.',
    authorName: 'Yumi',
    authorAvatarUrl: 'https://i.pravatar.cc/150?u=yumi',
    duration: '2-3h',
    priceRange: 'Free',
    tags: ['Historic', 'Photo Spot'],
  ),
  const ExperienceCardModel(
    id: '3',
    title: 'Sushi Zanmai',
    imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80&fit=crop',
    rating: 4.2,
    category: ExperienceCategory.restaurant,
    comment: 'Fresh sushi at a reasonable price.',
    authorName: 'Ken',
    authorAvatarUrl: 'https://i.pravatar.cc/150?u=ken',
    duration: '1.5h',
    priceRange: '\$\$\$',
    tags: ['Dinner', 'Seafood'],
  ),
  const ExperienceCardModel(
    id: '4',
    title: 'Joypolis',
    imageUrl: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=600&q=80&fit=crop',
    rating: 4.4,
    category: ExperienceCategory.amusement,
    comment: 'Fun indoor rides, perfect for dates!',
    authorName: 'Sora',
    authorAvatarUrl: 'https://i.pravatar.cc/150?u=sora',
    duration: '3h',
    priceRange: '\$\$\$',
    tags: ['Indoor', 'Date'],
  ),
];
